"""Build the set table embedded in one_click_armor_set.lua (between the SET TABLE markers).

Inputs:
  _research/equip_set/armor_sets.json      the kit table dumped by FileDiver's armor-set-json-dumper (NOTES.md 1)
  _research/equip_set/offers_25480438.log  the offers table dumped by recon 1 (NOTES.md 3): order, type, price

Rules (NOTES.md sections 1, 3, 7 and 20):
  1. Developer names: armor_/helmet_/cape_/banner_warbond_<group>_<n> form one set. Player cards (banner_*) aren't in
     the kit table, so their ids are the thin hashes of the names the kits imply.
  2. Other kits: a helmet and a body sharing a dlc_id form a set, plus a cape linked to that body through a dlc_id or
     a bundle set_id (not the catch-all sets 0 and 934502665).
  3. Superstore: each release block of the offers table carries one Super Credits armor with its cape and card, and
     the prices come in tiers (armor 250 -> cape 100, card 35; 300 -> 120, 40; 400 -> 250, 75). A Super Credits cape
     or card without a set joins the Super Credits armor of its tier within NEAR offers, when that pairing is the
     only one possible on both sides.
  4. Free sets: a free armor with no cape or card, and exactly one cape and one card without a set right beside it
     (ADJACENT offers), with no other armor that near them.
  5. CAPE_PAIRINGS: capes paired by hand with the armor sold on the same warbond page or in the same edition (HD2
     wiki, 2026-09-29), each moved into the set of the armor's body that players can own (the copy in the offers
     table), out of any other set.
Only sets with at least two different slots are kept. Set labels are the armor's English name (a number is added
when two sets share it).

Usage: python build_set_table.py
"""
import collections
import json
import re
import struct
import sys
from pathlib import Path

from crack_kit_names import thin

MOD = Path(__file__).resolve().parents[1]
SCRIPT = MOD / 'one_click_armor_set.lua'
RESEARCH = MOD.parent / '_research' / 'equip_set'
KITS = RESEARCH / 'armor_sets.json'
OFFERS = RESEARCH / 'offers_25480438.log'
# Name keys (name_upper) per kit, from HD2-Transmog's catalog of the same game build.
NAME_KEYS = MOD.parent / '_examples' / 'HD2-Transmog' / 'reference' / 'current_catalog.json'
BEGIN, END = '-- BEGIN SET TABLE (generated by research/build_set_table.py)\n', '-- END SET TABLE\n'
SLOT = {'Helmet': 'h', 'Armor': 'b', 'Cape': 'c'}
SLOT_WORD = {'h': 'helmet', 'b': 'armor', 'c': 'cape', 'p': 'card'}
CATCH_ALL_SETS = {0, 934502665}
SUPER_CREDITS = 0xcf875032
TIERS = {250: (100, 35), 300: (120, 40), 400: (250, 75)}  # armor price -> (cape price, card price)
NEAR, ADJACENT = 16, 3
# Rule 5: body item id -> cape item ids (both copies where the game has two of a cape).
CAPE_PAIRINGS = {
    # Helldivers Mobilize!: each page's armor with the page's cape.
    0x5bb4bbb0: [0x2cd5cfb0],              # SC-34 Infiltrator: Independence Bringer (P1)
    0xecabadbf: [0xd45f0974],              # FS-05 Marksman: Liberty's Herald (P2)
    0xfb4b1254: [0x8a5ec750],              # CE-35 Trench Engineer: Tideturner (P3)
    0x1c6c05fa: [0xee755525],              # CM-09 Bonesnapper: The Cape of Stars and Suffrage (P4)
    0xb513fd54: [0xa5a700cb, 0xf5dd3c6f],  # DP-40 Hero of the Federation: Unblemished Allegiance (P5)
    0x26d572a4: [0xc24b74f5],              # FS-23 Battle Master: Judgment Day (P6)
    0x1d60fc90: [0x53b64bf8],              # SC-30 Trailblazer Scout: Cresting Honor (P7)
    0xc9d2ad39: [0x32451e35],              # SA-04 Combat Technician: Mantle of True Citizenship (P8)
    0x38aa207d: [0xf8ea01ad],              # CM-14 Physician: Blazing Samaritan (P9)
    0xe3aaa79d: [0xdbf9ca34, 0x6e72f493],  # DP-11 Champion of the People: Light of Eternal Liberty (P10)
    # Steeled Veterans (page 2, SA-12 Servo-Assisted, has two capes: left out).
    0xdae4a744: [0x4100af4b],              # SA-25 Steel Trooper: Tyrant Hunter (P1)
    0x3c3ebaf0: [0x9e29ea2f],              # SA-32 Dynamo: Bastion of Integrity (P3)
    # Cutting Edge.
    0x24e3d6ba: [0x2bcc4463],              # EX-03 Prototype 3: Botslayer (P1)
    0xaa32b384: [0xc1105fbc],              # EX-16 Prototype 16: Martyris Rex (P2)
    0xd7b2fd5d: [0xf509b363],              # EX-00 Prototype X: Agent of Oblivion (P3)
    # Democratic Detonation.
    0x7edf6505: [0x1264718e],              # CE-27 Ground Breaker: Harbinger of True Equality (P1)
    0x5a17d6d6: [0x79a037c0],              # CE-07 Demolition Specialist: Eagle's Fury (P2)
    0xd3461392: [0x7d1003d0],              # FS-55 Devastator: Freedom's Tapestry (P3)
    # Super Citizen Edition.
    0xfd456de0: [0x77ae3af0],              # DP-53 Savior of the Free: Will of the People
    # Superstore, sold with the armor but far from it in the offers table (same 300 tier: cape 120).
    0xc60c706d: [0xf511b688],              # DS-10 Big Game Hunter: Eternal Corona
}
CARD_TYPE = 9


def kit_id(k):
    return int(k['id'], 16) if k['id'].startswith('0x') else thin(k['id'])


def load_offers(path):
    """Offers in table order: (index, item, type, currency, price)."""
    rows = []
    for line in open(path, encoding='utf-8'):
        if line.startswith('#'):
            continue
        i, e, _, s = line.split()
        e, s = bytes.fromhex(e), bytes.fromhex(s)
        rows.append((int(i), struct.unpack_from('<I', e, 8)[0], struct.unpack_from('<I', s, 12)[0],
                     struct.unpack_from('<I', s, 28)[0], struct.unpack_from('<I', s, 32)[0]))
    return rows


def base_sets(kits):
    sets = collections.defaultdict(dict)  # key -> {item id: slot}
    assigned = set()
    for k in kits:
        m = re.fullmatch(r'(armor|helmet|cape)_warbond_(.+)_(\d+)', k['id'])
        if m:
            key = 'w%s_%s' % (m.group(2), m.group(3))
            sets[key][kit_id(k)] = SLOT[k['kit_type']]
            assigned.add(kit_id(k))
    for key in list(sets):
        card = thin('banner_warbond_' + key[1:])
        sets[key][card] = 'p'
    by_dlc = collections.defaultdict(list)
    for k in kits:
        if kit_id(k) not in assigned and k['dlc_id'] != 0:
            by_dlc[k['dlc_id']].append(k)
    by_set = collections.defaultdict(list)
    for dlc, group in by_dlc.items():
        by_set[group[0]['set_id']].append(dlc)
    for dlc, group in by_dlc.items():
        slots = {SLOT[k['kit_type']] for k in group}
        if 'b' not in slots and 'h' not in slots:
            continue
        key = 'd%d' % dlc
        for k in group:
            sets[key][kit_id(k)] = SLOT[k['kit_type']]
    # Capes alone in their dlc, linked to exactly one body group through a bundle set_id.
    for dlc, group in by_dlc.items():
        if {SLOT[k['kit_type']] for k in group} != {'c'} or group[0]['set_id'] in CATCH_ALL_SETS:
            continue
        partners = [d for d in by_set[group[0]['set_id']] if d != dlc and 'd%d' % d in sets]
        if len(partners) == 1:
            for k in group:
                sets['d%d' % partners[0]][kit_id(k)] = 'c'
    return sets


def offer_rules(sets, slot_of, offers):
    """Rules 3 and 4: link capes and cards without a set to a neighboring armor of the same kind of release."""
    member = {item: key for key, m in sets.items() for item in m}
    first = {}  # item -> its first offer row
    for r in offers:
        first.setdefault(r[1], r)
    rows = sorted(first.values())

    def slot(r):
        return 'p' if r[2] == CARD_TYPE else slot_of.get(r[1])

    armors = collections.defaultdict(list)  # set key -> offer rows of its body and helmet (non-warbond sets)
    for r in rows:
        key = member.get(r[1])
        if key and key[0] == 'd' and slot(r) in ('b', 'h'):
            armors[key].append(r)
    orphans = [r for r in rows if slot(r) in ('c', 'p') and r[1] not in member]

    def has(key, s):
        return any(v == s for v in sets[key].values())

    def distance(r, key):
        return min(abs(r[0] - a[0]) for a in armors[key])

    links = []
    # Rule 3: Super Credits tiers.
    sc = {}
    for key, rs in armors.items():
        body = [r for r in rs if slot(r) == 'b' and r[3] == SUPER_CREDITS and r[4] in TIERS]
        if body:
            sc[key] = TIERS[body[0][4]]
    for s, t in (('c', 0), ('p', 1)):
        cand = collections.defaultdict(list)  # orphan -> armors it could join
        for r in orphans:
            if slot(r) == s and r[3] == SUPER_CREDITS:
                for key, prices in sc.items():
                    if prices[t] == r[4] and not has(key, s) and distance(r, key) <= NEAR:
                        cand[r].append(key)
        claims = collections.Counter(k for ks in cand.values() for k in ks)
        for r, ks in cand.items():
            if len(ks) == 1 and claims[ks[0]] == 1:
                links.append((r[1], ks[0], s, 'Superstore price tier'))
    # Rule 4: a free armor with exactly one cape and one card right beside it, and no other armor near them.
    free = [key for key, rs in armors.items() if all(r[3] != SUPER_CREDITS for r in rs)
            and not has(key, 'c') and not has(key, 'p')]
    for key in free:
        near = [r for r in orphans if r[3] != SUPER_CREDITS and distance(r, key) <= ADJACENT]
        if sorted(slot(r) for r in near) != ['c', 'p']:
            continue
        if any(other != key and distance(r, other) <= ADJACENT for r in near for other in armors):
            continue
        for r in near:
            links.append((r[1], key, slot(r), 'beside its armor'))
    for item, key, s, how in links:
        sets[key][item] = s
    return links


def cape_pairings(sets):
    """Rule 5: each paired cape into its armor's set, out of any other."""
    for body, capes in CAPE_PAIRINGS.items():
        key = next(k for k, m in sets.items() if m.get(body) == 'b')
        for cape in capes:
            for m in sets.values():
                m.pop(cape, None)
            sets[key][cape] = 'c'


def english_labels(sets, by_id):
    """Set key -> label: the armor's English name (else the helmet's), numbered when two sets share it."""
    raw = {}
    for key, members in sets.items():
        name = None
        for s in ('b', 'h'):
            named = sorted(i for i, v in members.items() if v == s and i in by_id
                           and not re.fullmatch(r'[0-9a-f]{5,8}', by_id[i]['name']))
            if named:
                name = by_id[named[0]]['name']
                break
        # Prefer a mixed-case spelling of the same name (some armors are named in capitals, their helmets not).
        spellings = [by_id[i]['name'] for i in sorted(members) if i in by_id]
        name = next((n for n in spellings if name and n.lower() == name.lower() and n != n.upper()), name)
        raw[key] = name or 'Unnamed %s' % key[1:]
    count = collections.Counter(raw.values())
    seen = collections.Counter()
    labels = {}
    for key in sorted(sets, key=lambda k: (raw[k], min(sets[k]))):
        n = raw[key]
        seen[n] += 1
        labels[key] = n if count[n] == 1 else '%s (%d)' % (n, seen[n])
    return labels


def build():
    kits = json.load(open(KITS, encoding='utf-8'))
    by_id = {kit_id(k): k for k in kits}
    slot_of = {i: SLOT[k['kit_type']] for i, k in by_id.items()}
    sets = base_sets(kits)
    offers = load_offers(OFFERS)
    links = offer_rules(sets, slot_of, offers)
    cape_pairings(sets)
    sets = {key: m for key, m in sets.items() if len(set(m.values())) >= 2}
    labels = english_labels(sets, by_id)
    table = {}  # item -> (label, slot)
    for key, m in sets.items():
        for item, s in m.items():
            table[item] = (labels[key], s)
    names = set_names(table, by_id, json.load(open(NAME_KEYS, encoding='utf-8'))['kits'])
    return table, names, by_id, links


def set_names(table, by_id, name_keys):
    """Per set: the armor's localization key (else the helmet's) and its English name as a fallback."""
    members = collections.defaultdict(list)
    for item, (label, s) in table.items():
        members[label].append((item, s))
    names = {}
    for label, ms in members.items():
        for s in ('b', 'h'):
            named = sorted(i for i, v in ms if v == s and i in by_id
                           and not re.fullmatch(r'[0-9a-f]{5,8}', by_id[i]['name']))
            if named:
                names[label] = (name_keys.get(str(named[0]), {}).get('name_upper', 0), by_id[named[0]]['name'].upper())
                break
    return names


def lua_string(s):
    return "'%s'" % s.replace('\\', '\\\\').replace("'", "\\'")


def lua_block(table, names):
    lines = [BEGIN, '-- [item id] = {set, slot}: slot h helmet, b body, c cape, p player card\n', 'local SETS = {\n']
    for item, (label, s) in sorted(table.items(), key=lambda x: (x[1][0], 'hbcp'.index(x[1][1]), x[0])):
        lines.append('    [0x%08x] = {%s, %s},\n' % (item, lua_string(label), lua_string(s)))
    lines += ['}\n', '-- [set] = {localization key of its armor name, English name}\n', 'local SET_NAMES = {\n']
    for label in sorted(names):
        loc, en = names[label]
        lines.append('    [%s] = {0x%08x, %s},\n' % (lua_string(label), loc, lua_string(en)))
    lines += ['}\n', END]
    return ''.join(lines)


def main():
    table, names, by_id, links = build()
    text = SCRIPT.read_text(encoding='utf-8')
    a, b = text.index(BEGIN), text.index(END) + len(END)
    SCRIPT.write_bytes((text[:a] + lua_block(table, names) + text[b:]).encode('utf-8'))
    for item, key, s, how in links:
        print('linked %s %08x %-34s -> %s (%s)' % (SLOT_WORD[s], item, by_id[item]['name'] if item in by_id else '',
                                                 key, how))
    labels = collections.Counter(label for label, _ in table.values())
    slots = collections.Counter(''.join(sorted({s for i, (l, s) in table.items() if l == label}, key='hbcp'.index))
                                for label in labels)
    print('%d sets, %d items: %s' % (len(labels), len(table), dict(slots)))
    print('%d set names, %d without a localization key' % (len(names), sum(1 for v in names.values() if not v[0])))


if __name__ == '__main__':
    sys.exit(main())
